#!/usr/bin/env python3
"""Choose host folders for Docker Compose without editing the base Compose file."""

import argparse
import json
import os
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OVERRIDE = ROOT / "compose.override.yaml"
MARKER = "x-solar-forge-storage"


def _folder(value: str, label: str) -> Path:
    path = Path(value).expanduser().resolve()
    if not Path(value).expanduser().is_absolute():
        raise ValueError(f"{label} must be an absolute path.")
    if path == ROOT or ROOT in path.parents:
        raise ValueError(f"{label} must be outside the repository.")
    if path.exists() and not path.is_dir():
        raise ValueError(f"{label} is not a folder: {path}")
    return path


def build_override(data: Path, backup: Path, previous_data: Path | None) -> dict:
    previous = (
        {"type": "bind", "source": str(previous_data), "target": "/previous-data",
         "read_only": True, "bind": {"create_host_path": False}}
        if previous_data else
        {"type": "volume", "source": "solar_forge_desktop_data",
         "target": "/previous-data", "read_only": True}
    )
    return {
        MARKER: {"version": 1, "data": str(data), "backup": str(backup)},
        "services": {"desktop": {
            "environment": {"SOLAR_FORGE_DESKTOP_PREVIOUS_DATA_DIR": "/previous-data"},
            "volumes": [
                {"type": "bind", "source": str(data), "target": "/data",
                 "bind": {"create_host_path": False}},
                {"type": "bind", "source": str(backup), "target": "/backups",
                 "bind": {"create_host_path": False}},
                previous,
            ],
        }},
    }


def configure(data_value: str, backup_value: str) -> tuple[Path, Path]:
    data = _folder(data_value, "Data folder")
    backup = _folder(backup_value, "Backup folder")
    if data == backup:
        raise ValueError("Choose different data and backup folders.")
    previous_data = None
    if OVERRIDE.exists():
        try:
            old = json.loads(OVERRIDE.read_text(encoding="utf-8"))
            marker = old[MARKER]
            if marker["version"] != 1:
                raise ValueError("Unsupported storage override version.")
            previous_data = Path(marker["data"])
        except (ValueError, KeyError, TypeError) as exc:
            raise ValueError(
                "compose.override.yaml was not generated by this command; leave it intact."
            ) from exc
        if not previous_data.is_dir():
            raise ValueError(f"The previous data folder is unavailable: {previous_data}")
    data.mkdir(parents=True, exist_ok=True)
    backup.mkdir(parents=True, exist_ok=True)
    document = build_override(data, backup, previous_data)
    fd, temporary_name = tempfile.mkstemp(prefix=".compose-storage-", dir=ROOT)
    temporary = Path(temporary_name)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as stream:
            json.dump(document, stream, indent=2)
            stream.write("\n")
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary, OVERRIDE)
    finally:
        temporary.unlink(missing_ok=True)
    return data, backup


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data", help="absolute host folder for the SQLite database")
    parser.add_argument("--backup", help="absolute host folder for future backups")
    args = parser.parse_args()
    data_value = args.data or input("Data folder (absolute path): ").strip()
    backup_value = args.backup or input("Backup folder (absolute path): ").strip()
    try:
        data, backup = configure(data_value, backup_value)
    except (OSError, ValueError) as exc:
        parser.exit(1, f"Storage setup failed: {exc}\n")
    print(f"Compose data folder: {data}")
    print(f"Compose backup folder: {backup}")
    print("Start with `docker compose up --build` after closing any running app.")
    print("An existing database is copied from the previous Compose location on first start.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
